package proy.modelo.entidad;
// Generated 05/06/2015 10:40:13 PM by Hibernate Tools 4.3.1



/**
 * Boleto generated by hbm2java
 */
public class Boleto  implements java.io.Serializable {

    public String getBoletos() {
        return boletos;
    }

    public void setBoletos(String boletos) {
        this.boletos = boletos;
    }


     private String idBoleto;
     private String idPasajero;
     private String idViaje;
     private String valorPagar;
     private String boletos;

    public Boleto() {
    }

    public String getIdBoleto() {
        return idBoleto;
    }

    public void setIdBoleto(String idBoleto) {
        this.idBoleto = idBoleto;
    }

    public String getIdPasajero() {
        return idPasajero;
    }

    public void setIdPasajero(String idPasajero) {
        this.idPasajero = idPasajero;
    }

    public String getIdViaje() {
        return idViaje;
    }

    public void setIdViaje(String idViaje) {
        this.idViaje = idViaje;
    }

    public String getValorPagar() {
        return valorPagar;
    }

    public void setValorPagar(String valorPagar) {
        this.valorPagar = valorPagar;
    }
}


