package proy.modelo.entidad;
// Generated 05/06/2015 10:40:13 PM by Hibernate Tools 4.3.1




/**
 * Conductor generated by hbm2java
 */
public class Conductor  implements java.io.Serializable {


     private String idConductor;
     private String nroLicencia;
     private String nombres;
     private String apellidos;
     private String fecha_viaje;
     private String hora_viaje;
     private String ciudad_salida;
     private String ciudad_destino;
     private String nro_placa;
     private String id_viajes;

    public Conductor() {
    }

    public String getId_viajes() {
        return id_viajes;
    }

    public void setId_viajes(String id_viajes) {
        this.id_viajes = id_viajes;
    }

    public String getNro_placa() {
        return nro_placa;
    }

    public void setNro_placa(String nro_placa) {
        this.nro_placa = nro_placa;
    }

    public String getIdConductor() {
        return idConductor;
    }

    public void setIdConductor(String idConductor) {
        this.idConductor = idConductor;
    }

    public String getNroLicencia() {
        return nroLicencia;
    }

    public void setNroLicencia(String nroLicencia) {
        this.nroLicencia = nroLicencia;
    }

    public String getNombres() {
        return nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getApellidos() {
        return apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public String getFecha_viaje() {
        return fecha_viaje;
    }

    public void setFecha_viaje(String fecha_viaje) {
        this.fecha_viaje = fecha_viaje;
    }

    public String getHora_viaje() {
        return hora_viaje;
    }

    public void setHora_viaje(String hora_viaje) {
        this.hora_viaje = hora_viaje;
    }

    public String getCiudad_salida() {
        return ciudad_salida;
    }

    public void setCiudad_salida(String ciudad_salida) {
        this.ciudad_salida = ciudad_salida;
    }

    public String getCiudad_destino() {
        return ciudad_destino;
    }

    public void setCiudad_destino(String ciudad_destino) {
        this.ciudad_destino = ciudad_destino;
    }
   
}


