package proy.modelo.entidad;
// Generated 05/06/2015 10:40:13 PM by Hibernate Tools 4.3.1


/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo {


     private String idVehiculo;
     private String idMarca;
     private String idColor;
     private String idModelo;
     private String nroPlaca;
 

    public Vehiculo() {
    }

    public String getIdVehiculo() {
        return idVehiculo;
    }

    public void setIdVehiculo(String idVehiculo) {
        this.idVehiculo = idVehiculo;
    }

    public String getIdMarca() {
        return idMarca;
    }

    public void setIdMarca(String idMarca) {
        this.idMarca = idMarca;
    }

    public String getIdColor() {
        return idColor;
    }

    public void setIdColor(String idColor) {
        this.idColor = idColor;
    }

    public String getIdModelo() {
        return idModelo;
    }

    public void setIdModelo(String idModelo) {
        this.idModelo = idModelo;
    }

    public String getNroPlaca() {
        return nroPlaca;
    }

    public void setNroPlaca(String nroPlaca) {
        this.nroPlaca = nroPlaca;
    }

}


