package proy.modelo.entidad;
// Generated 05/06/2015 10:40:13 PM by Hibernate Tools 4.3.1

/**
 * Viajes generated by hbm2java
 */
public class Viajes  implements java.io.Serializable {


     private String idViajes;
     private String IdCiudaddestino;
     private String IdCiudad;
     private String idVehiculo;
     private String idConductor;
     private String horaViaje;
     private String fechaViaje;
  

    public Viajes() {
    }

    public String getIdViajes() {
        return idViajes;
    }

    public void setIdViajes(String idViajes) {
        this.idViajes = idViajes;
    }

    public String getIdCiudaddestino() {
        return IdCiudaddestino;
    }

    public void setIdCiudaddestino(String IdCiudaddestino) {
        this.IdCiudaddestino = IdCiudaddestino;
    }

    public String getIdCiudad() {
        return IdCiudad;
    }

    public void setIdCiudad(String IdCiudad) {
        this.IdCiudad = IdCiudad;
    }

    public String getIdVehiculo() {
        return idVehiculo;
    }

    public void setIdVehiculo(String idVehiculo) {
        this.idVehiculo = idVehiculo;
    }

    public String getIdConductor() {
        return idConductor;
    }

    public void setIdConductor(String idConductor) {
        this.idConductor = idConductor;
    }

    public String getHoraViaje() {
        return horaViaje;
    }

    public void setHoraViaje(String horaViaje) {
        this.horaViaje = horaViaje;
    }

    public String getFechaViaje() {
        return fechaViaje;
    }

    public void setFechaViaje(String fechaViaje) {
        this.fechaViaje = fechaViaje;
    }



}


